LibraryProject/Models/Kind.cs
using System.ComponentModel.DataAnnotations;

namespace LibraryProject.Models
{
    public class Kind
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public ICollection<Book> BookList { get; set; } = new List<Book>();

    }
}

LibraryProject/Controllers/KindController.cs
using LibraryProject.Models;
using LibraryProject.Repositories;
using LibraryProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LibraryProject.Controllers
{
    [Authorize(Roles = "admin")]
    public class KindController : Controller
    {
        private readonly IKindrepo kindrepo;

        public KindController(IKindrepo _kindrepo)
        {
            kindrepo = _kindrepo;
        }
        public IActionResult Index()
        {
            var allkinds = kindrepo.GetAll();
            var allkindVMs =new List<KindVM>();

            if(allkinds != null)
            {
                foreach(var kind in allkinds)
                {
                    var kindVM =new KindVM();
                    kindVM.Id = kind.Id;
                    kindVM.Name = kind.Name;
                    allkindVMs.Add(kindVM);
                }
            }
            return View(allkindVMs);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(KindVM kindVM)
        {
            if (ModelState.IsValid)
            {
                var kind = new Kind();
                kind.Name = kindVM.Name;

                kindrepo.Add(kind);
                kindrepo.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(kindVM);
            }
        }

        public IActionResult Edit(int Id)
        {
            if (Id == null || Id == 0)
                return NotFound();
            else
            {
                var kind = kindrepo.GetById(Id);
                if (kind == null)
                    return NotFound();

                var kindVM = new KindVM();
                kindVM.Id = kind.Id;
                kindVM.Name = kind.Name;
                return View(kindVM);
            }

        }
        [HttpPost]
        public IActionResult Edit(KindVM kindVM)
        {
            if (ModelState.IsValid)
            {
                var kind = kindrepo.GetById(kindVM.Id);
                if (kind == null)
                    return View(kindVM);

                kind.Name = kindVM.Name;
                kindrepo.Update(kind);
                kindrepo.SaveChanges();
                return RedirectToAction("index");
            }
            else
            {
                return View(kindVM);
            }
        }
        public IActionResult Delete(int Id)
        {
            if (Id == null || Id == 0)
                return NotFound();
            var kind = kindrepo.GetById(Id);
            if (kind != null)
            {
                var kindVM = new KindVM();
                kindVM.Id = kind.Id;
                kindVM.Name = kind.Name;
                return View(kindVM);
            }
            return NotFound();
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(KindVM kindVM)
        {
            if (kindVM.Id == 0)
            {
                return NotFound();
            }
            var kind = kindrepo.GetById(kindVM.Id);
            if (kind != null)
            {
                kindrepo.Remove(kind);
                kindrepo.SaveChanges();
                return RedirectToAction("index");
            }
            return NotFound();

        }


    }
}

LibraryProject/Views/Kind/Create.cshtml
@{
    ViewData["Title"] = "Create";
}.
@model KindVM

<div class="border-0 card shadow my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Kind</h2>
            </div>
        </div>
    </div>
  <div class="card-body p-4">
    <form asp-action="Create">
   
        <div class="mb-3 row p-1">
            <label class="p-0">Kind Name</label>
            <input type="text" class="form-control" asp-for="@Model.Name" />
            <span class="text-danger" asp-validation-for="@Model.Name"></span>
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Kind" asp-action="index" class="btn btn-secondary border form-control">
                    Back to List
                </a>

            </div>
        </div>
   
      </form>
    </div>
</div>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

LibraryProject/Views/Kind/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}
@model KindVM

<div class="border-0 card shadow my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Kind</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form asp-action="Delete">
            <input asp-for="Id" class="d-none"/>
            <div class="mb-3 row p-1">
                <label class="p-0">Kind Name</label>
                <input type="text" class="form-control" asp-for="@Model.Name"readonly />
            </div>
            <div class="row">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-primary form-control">Delete</button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="Kind" asp-action="index" class="btn btn-secondary border form-control">
                        Back to List
                    </a>

                </div>
            </div>
        </form>

    </div>
</div>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

LibraryProject/Views/Kind/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}
@model KindVM
<div class="border-0 card shadow my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Edit Kind</h2>
            </div>
        </div>
    </div>
<div class="card-body p-4">
<form asp-action="Edit">
        <input asp-for="Id" hidden />
        <div class="mb-3 row p-1">
            <label class="p-0">Kind Name</label>
            <input type="text" class="form-control" asp-for="@Model.Name" />
            <span class="text-danger" asp-validation-for="@Model.Name"></span>
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Kind" asp-action="index" class="btn btn-secondary border form-control">
                    Back to List
                </a>

            </div>
        </div>

      </form>
    </div>
</div>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

LibraryProject/Views/Kind/Index.cshtml
@model List<KindVM>
<div class="container">
    <div class="row pt-4 pb-3 ">
        <div class="col-6">
            <h2 class="text-primary">
                Kind List
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-circle"></i>Create New Kind</a>
        </div>

    </div>
</div>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                Kind Name
            </th>

            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        { if (item != null)
            {
                <tr>
                    <td>@item.Name</td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-action="Edit" class="btn btn-primary mx-2" asp-route-Id="@item.Id">
                              <i class="bi bi-pencil-square"></i>Edit
                        </a>
                        <a asp-action="Delete" class="btn btn-danger mx-2" asp-route-Id="@item.Id">
                            <i class="bi bi-trash-fill"></i>Delete
                        </a>
                    </div>
                </td>
              
            </tr>
            }
        }
    </tbody>

</table>