LibraryProject/Controllers/BookController.cs
using LibraryProject.Models;
using LibraryProject.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Collections.Generic;

namespace LibraryProject.Controllers
{
	public class BookController : Controller
	{
		IBookRepo bookRepository;
        public BookController(IBookRepo _context)
        {
			bookRepository = _context;
        }

        public IActionResult AllBooks()
		{
		
			List<Book> books = bookRepository.GetAll();
			ViewData["books"] = books;
			return View("BookView", books);
		}
        [Authorize(Roles = "admin")]
        public IActionResult Add()
		{
			return View("AddView");
		}

		public IActionResult SaveAdd(Book Newbook)
		{
			if (Newbook.Title != null)
			{
			bookRepository.Add(Newbook);
			bookRepository.Save();
            return RedirectToAction("AllBooks");
			}
			
		    return View("AddView" , Newbook);
			
		;
		}
        [Authorize(Roles = "admin")]
        public IActionResult Edit(int id)
		{
			Book book = bookRepository.GetById(id);
			return View("EditView" ,book);
		}

		[HttpPost]
	public IActionResult SaveEdit(Book EditedBook , int id)
		{
			if (EditedBook.Title != null)
			{
				Book bookEdit = bookRepository.GetById(id);
				bookEdit.Title = EditedBook.Title;
				bookEdit.Author = EditedBook.Author;
				bookEdit.StatusId = EditedBook.StatusId;
			    bookRepository.Save();
				return RedirectToAction("AllBooks");

			}

				return View("EditView", EditedBook);
			

		}

        [Authorize(Roles = "admin")]
        //public IActionResult Delete(Book book, int id)
        public async Task<IActionResult> Delete(Book book, int id)
        {
			bookRepository.Delete(id);
			bookRepository.Save();
			return RedirectToAction("AllBooks");
		}




        public IActionResult Search(string author)
        {

            List<Book> bookAuthor = bookRepository.Search(author);
            if (bookAuthor.Any())
            {
                ViewData["AuthorName"] = $"{author}";
                ViewBag.BookAuthor = bookAuthor;
                return View("SearchView", bookAuthor);
            }


            ViewBag.Message = $"No books found by this author {author}";
            return View("SearchView", ViewBag.Message);


            //return View();

        }

    }

}

LibraryProject/Controllers/BorrowController.cs
using LibraryProject.Migrations;
using LibraryProject.Models;
using LibraryProject.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol;

namespace LibraryProject.Controllers
{
    [Authorize(Roles = "admin")]
    public class BorrowController : Controller
    {
        IBorrowRepo borrowRepository;
        IBookRepo bookRepository;
        public BorrowController(IBorrowRepo _borrowcontext, IBookRepo _bookRepository)
        {
            borrowRepository = _borrowcontext;
            bookRepository = _bookRepository;
        }
        // /Borrow/AllBorrowings
        public IActionResult AllBorrowings()
        {
            List<Borrowing> borrowings = borrowRepository.GetAll();
            ViewData["borrowings"] = borrowings;
            ViewData["User"] = borrowRepository.GetAllUsers();
            return View("AllBorrowings", borrowings);
        }
        // /Borrow/CreateBorrow
        [HttpGet]
        public IActionResult CreateBorrow()
        {
            //Borrowing borrowing = new Borrowing();
            //borrowing.ActualReturnDate = borrowing.DueDate;

            ViewBag.Books = bookRepository.GetAll();
            ViewBag.Users = borrowRepository.GetAllUsers();


            return View("CreateBorrow");
        }
        [HttpPost]
        public IActionResult SaveNewBorrow(Borrowing BorrowFromRequest)
        {
            if (ModelState.IsValid == true)
            {
                //BorrowFromRequest.ActualReturnDate=BorrowFromRequest.DueDate;

                // Save

                borrowRepository.AddBorrowing(BorrowFromRequest); 
                BorrowFromRequest.ActualReturnDate=BorrowFromRequest.DueDate;
                //Add();
                borrowRepository.Save();
                return RedirectToAction("AllBorrowings");
            }
            ViewBag.Books = bookRepository.GetAll();
            ViewBag.Users = borrowRepository.GetAllUsers();
            return View("CreateBorrow", BorrowFromRequest);

    }
        public double CalcPenality(DateTime dayD, DateTime dayAct) {
            Borrowing br = new Borrowing();
            var numDays = (dayAct - dayD).Days;

            return 5 * numDays;
        }
   
        public IActionResult EditBorrow(int id) 
        {
            ViewBag.Books = bookRepository.GetAll();
            ViewBag.Users = borrowRepository.GetAllUsers();
            Borrowing _borrowing=borrowRepository.GetById(id);
            List<Book> books = bookRepository.GetAll();
            _borrowing.Id = id;
            
            //_borrowing.PenalityAmount = CalcPenality(_borrowing.DueDate, _borrowing.ActualReturnDate);
            return View("EditBorrow",_borrowing);
            
        }
        [HttpPost]
        public IActionResult SaveEdit(int id,Borrowing borrowFromRequest)
        {
            //ViewData["BookList"] = bookRepository.GetAll();
            //ViewData["UsersList"] = borrowRepository.GetAllUsers();
            if (borrowRepository.GetById(id) != null)
            {
                Borrowing borrowFromDB=borrowRepository.GetById(id);
                borrowFromDB.BookId = borrowFromRequest.BookId;
                borrowFromDB.ApplicationUserId = borrowFromRequest.ApplicationUserId;
                borrowFromDB.BorrowingDate = borrowFromRequest.BorrowingDate;
                borrowFromDB.DueDate = borrowFromRequest.DueDate;
                borrowFromDB.ActualReturnDate = borrowFromRequest.ActualReturnDate;
                borrowFromDB.PenalityAmount = borrowFromRequest.PenalityAmount;
                borrowFromDB.PenalityAmount = CalcPenality(borrowFromDB.DueDate, borrowFromDB.ActualReturnDate);


                borrowRepository.UpdateBorrowing(borrowFromDB);
                borrowRepository.Save();
                return RedirectToAction("AllBorrowings");
            }
            //borrowRepository.Save();

            return View("EditBorrow", borrowFromRequest);

        }

        public async Task<IActionResult> DeleteBorrow(Borrowing _borrow, int id)
        {
            borrowRepository.DeleteBorrowing(id);
            borrowRepository.Save();
            return RedirectToAction("AllBorrowings");
        }
        public ActionResult BorrowForEachBook(int id,Book _book) {
            //bookRepository.AddBook(id);
			//borrowRepository.UpdateBorrowing();
            ViewBag.BookID=bookRepository.GetById(id);
			borrowRepository.Save();
			return RedirectToAction("CreateBorrow");
        }



    }
}

LibraryProject/Views/Borrow/AllBorrowings.cshtml
@model List<Borrowing>
@{
    ViewData["Title"] = "AllBorrowings";
}

<div class="container">
    <div class="row pt-4 pb-3 ">
        <div class="col-6">
            <h2 class="text-primary">
                All Borroings
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-action="CreateBorrow" asp-controller="Borrow" class="btn btn-primary"><i class="bi bi-plus-circle"></i>Create Borrow</a>
        </div>

    </div>
</div>
<table class="table table-bordered table-hover">
    <tr>
        <th>BorrowId</th>
        <th>BookId</th>
        <th>UserName</th>
        <th>Borrowing-Date</th>
        <th>DueDate</th>
        <th>ActualReturnDate</th>
        <th>Penality</th>
        <th colspan="2">Actions</th>
    </tr>

    @foreach(var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.BookId</td>
            <td>@item.ApplicationUser.UserName</td>
            <td>@item.BorrowingDate</td>
            <td>@item.DueDate</td>
            <td>@item.ActualReturnDate</td>
            <td>@item.PenalityAmount</td>
            <td>
                <a href="/Borrow/EditBorrow/@item.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
            </td>
            <td>

                <a href="/Borrow/DeleteBorrow/@item.Id" class="btn btn-danger mx-2"><i class="bi bi-trash-fill"></i>Delete</a>
            </td>
                 @* <button type="submit" class="btn btn-danger">Delete</button> *@
        </tr>
    }
</table>

LibraryProject/Views/Borrow/CreateBorrow.cshtml
@model Borrowing
@{
    ViewData["Title"] = "CreateBorrow";
    SelectList BookOptions = new SelectList(ViewBag.Books, "Id", "Title");
    SelectList UserOptions = new SelectList(ViewBag.Users,"Id","UserName");
    // SelectList BookID = new SelectList(ViewBag.BookID, "Id", "Title");
}

<h1>CreateBorrow</h1>
<form method="post" asp-action="SaveNewBorrow" asp-controller="Borrow" >

  @*   <div>
        <label asp-for="Id"></label>
        <input class="form-check form-control" asp-for="Id"/>
    </div> *@

    <div>
       @*  <label asp-for="BookId"></label>
        <input class="form-check form-control" asp-for="BookId" /> *@

        <label asp-for="BookId"></label>
        <select class="form form-control"
                asp-for="BookId"
                asp-items="BookOptions">
            <option value="0">---Select Book---</option>
        </select>
    

         
    </div>

    <div>
        @* <label asp-for="ApplicationUserId"></label>
        <input class="form-check form-control" asp-for="ApplicationUserId" /> *@
        <label asp-for="ApplicationUserId"></label>
        <select class="form form-control"
                asp-for="ApplicationUserId"
                asp-items="UserOptions">
            <option value="0">---Select User---</option>
        </select>
    </div>

    <div>
        <label asp-for="BorrowingDate"></label>
        <input class="form-check form-control" asp-for="BorrowingDate" />
    </div>

    <div>
        <label asp-for="DueDate"></label>
        <input class="form-check form-control" asp-for="DueDate" />
    </div>

    <div>
        <label asp-for="ActualReturnDate"></label>
        <input class="form-check form-control" asp-for="ActualReturnDate" />
    </div>

    <div>
        <label asp-for="PenalityAmount"></label>
        <input class="form-check form-control" asp-for="PenalityAmount" />
    </div>

    <input type="submit" value="Create" class="btn btn-success" />

</form>

<a asp-action="AllBooks" asp-controller="Book">Back To BookList</a>

LibraryProject/Views/Borrow/EditBorrow.cshtml
@model Borrowing
@{
    ViewData["Title"] = "EditBorrow";
    SelectList BookOptions = new SelectList(ViewBag.Books, "Id", "Title");
    SelectList UserOptions = new SelectList(ViewBag.Users, "Id", "UserName");
}

 @* <h1>EditBorrow</h1>

 <form method="post" asp-action="SaveEdit" asp-controller="Borrow" asp-route-id="@Model.Id">
     <div>
       
         <label asp-for="BookId"></label>
         <select class="form form-control"
                 asp-for="BookId"
                 asp-items="BookOptions">
             <option value="0">---Select Book---</option>
         </select>
     </div>

     <div>
        
         <label asp-for="ApplicationUserId"></label>
         <select class="form form-control"
                 asp-for="ApplicationUserId"
                 asp-items="UserOptions">
             <option value="0">---Select User---</option>
         </select>
     </div>

     <div>
         <label asp-for="BorrowingDate"></label>
         <input class="form-check form-control" asp-for="BorrowingDate" />
     </div>

     <div>
         <label asp-for="DueDate"></label>
         <input class="form-check form-control" asp-for="DueDate" />
     </div>

     <div>
         <label asp-for="ActualReturnDate"></label>
         <input class="form-check form-control" asp-for="ActualReturnDate" />
     </div>

     <div>
         <label asp-for="PenalityAmount"></label>
         <input class="form-check form-control" asp-for="PenalityAmount" />
     </div>

     <input type="submit" value="Save-Edits" class="btn btn-success" />


 </form>
 <a asp-action="AllBorrowings" asp-controller="Borrow">Back</a> *@.

<div class="border-0 card shadow my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Edit Borrow</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">


        <form method="post" asp-action="SaveEdit" asp-controller="Borrow" asp-route-id="@Model.Id">
            <div>

                <label asp-for="BookId"></label>
                <select class="form form-control"
                        asp-for="BookId"
                        asp-items="BookOptions">
                    <option value="0">---Select Book---</option>
                </select>
            </div>

            <div>

                <label asp-for="ApplicationUserId"></label>
                <select class="form form-control"
                        asp-for="ApplicationUserId"
                        asp-items="UserOptions">
                    <option value="0">---Select User---</option>
                </select>
            </div>

            <div>
                <label asp-for="BorrowingDate"></label>
                <input class="form-check form-control" asp-for="BorrowingDate" />
            </div>

            <div>
                <label asp-for="DueDate"></label>
                <input class="form-check form-control" asp-for="DueDate" />
            </div>

            <div>
                <label asp-for="ActualReturnDate"></label>
                <input class="form-check form-control" asp-for="ActualReturnDate" />
            </div>

            <div>
                <label asp-for="PenalityAmount"></label>
                <input class="form-check form-control" asp-for="PenalityAmount" />
            </div>
            <div class="row">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-primary form-control">Save Edits</button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="Borrow" asp-action="AllBorrowings" class="btn btn-secondary border form-control">
                        Back
                    </a>

                </div>
            </div>

        </form>
    </div>
</div>